# Generated by Django 2.2.13 on 2021-01-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenericViewPractices', '0002_auto_20201227_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
